config/routes.rb
Rails.application.routes.draw do
  root to: "ratings#approval"
  match 'register', to: 'users#register', via: [:post]
  match 'upload_user_avatar', to: 'users#upload_user_avatar', via: [:post, :patch]
  # match 'upload_road_photo', to: 'ratings#upload_road_photo', via: [:post, :patch]
  match 'upload', to: 'users#index', via: [:get]

  namespace :admin do
    resources :countries
    resources :districts
    resources :profiles
    resources :role_types
    resources :states
    resources :taluks
    resources :users
    resources :users_roles_maps
    resources :wards
    resources :zones
    root to: "countries#index"
  end

  resources :roads do
    resources :complaints, only: [:show, :create, :index]
  end

  resources :ratings do
    collection do
      get :reset
    end
    member do
      get :approve
      get :reject
    end
  end
  get 'approval', to: 'ratings#approval'
  resources :profiles
  resources :dashboard
  resources :users_roads_photo_maps
  resources :roads, defaults: {format: :json} do
    member do
      get :info
    end
  end
  resources :users do
    member do
      get :my_uploads
    end
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  enum status: [:pending, :approve, :reject]
  belongs_to :road
  belongs_to :user

  def photos_map
    UsersRoadsPhotoMap.where(user: user, road: road)
  end

  def photos
    @photos ||= UsersRoadsPhotoMap.where(road: road, user: user).map { |photo_map|
      { thumbnail: photo_map.photo.url(:thumb),  original: photo_map.photo.url}
    }
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy, :approve, :reject]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all.includes(:road, :user)
  end

  def approval
    @ratings = Rating.where(status: :pending).includes(:road, :user)
  end

  def approve
    @rating.approve!
    redirect_to approval_path, notice: 'Successfully Approved'
  end

  def reject
    @rating.reject!
    redirect_to approval_path, notice: 'Successfully Rejected'
  end

  def reset
    Rating.all.each do |rating|
      rating.status = :pending
      rating.save!
    end
    redirect_to approval_path
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)
    if @rating.save
      render json: @rating, status: 201
    else
      render json: @rating.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_rating
    @rating = Rating.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def rating_params
    all_rating_params = params[:rating] ? params.require(:rating) : params
    all_rating_params.permit(:user_id, :road_quality, :encroachment, :platform_usability, :safety, :comments, :road_id, :photo)
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
  def star_html(count=1)
    final_html = ''
    5.times do |num|
      final_html += "<option value='#{num}' #{num==(count-1) ? 'selected' : ''}>#{num}</option>"
    end
    "<select class='rating'>
      #{final_html}
    </select>".html_safe
  end
end

app/views/ratings/_form.html.erb
<%= form_for(rating) do |f| %>
  <% if rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :road_quality %>
    <%= f.number_field :road_quality %>
  </div>

  <div class="field">
    <%= f.label :encroachment %>
    <%= f.number_field :encroachment %>
  </div>

  <div class="field">
    <%= f.label :platform_usability %>
    <%= f.number_field :platform_usability %>
  </div>

  <div class="field">
    <%= f.label :safety %>
    <%= f.number_field :safety %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <div class="field">
    <%= f.label :road_id %>
    <%= f.number_field :road_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/_star.html.erb
<select class="rating">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4" selected="">4</option>
  <option value="5">5</option>
</select>

app/views/ratings/approval.html.erb
<p id="notice"><%= notice %></p>

<h4>Approve Submissions</h4>

<% if @ratings.size <= 0 %>
  <p>No submissions left to approve!</p>
<% else %>
  <table class="highlight">
    <thead>
      <tr>
        <th>Road</th>
        <th>Platform</th>
        <th>Safety</th>
        <th>Quality</th>
        <th>Encroachment</th>
        <th>Approve?</th>
      </tr>
    </thead>

    <tbody>
      <% @ratings.each do |rating| %>
        <tr>
          <td>
            <%= rating.road.summary %><br>
            <% rating.photos.each do |photo| %>
              <a class="fancybox" rel="group" href="<%= photo[:original] %>">
                <img class='thumbsize img-circle' src="<%= photo[:thumbnail] %>" alt="" />
              </a>
            <% end %>
          </td>
          <td><%= star_html(rating.platform_usability) %></td>
          <td><%= star_html(rating.safety) %></td>
          <td><%= star_html(rating.road_quality) %></td>
          <td><%= star_html(rating.encroachment) %></td>
          <td>
            <%= link_to 'Yes', approve_rating_path(rating.id) %> /
            <%= link_to 'No', reject_rating_path(rating.id) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <script type='text/javascript'>
    $(document).ready(function() {
      $(".fancybox").fancybox();
      $('.rating').barrating({
        theme: 'fontawesome-stars',
        readonly: true
      });
    });
  </script>

<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Road quality</th>
      <th>Encroachment</th>
      <th>Platform usability</th>
      <th>Safety</th>
      <th>Comments</th>
      <th>Road</th>
      <th>User</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.road_quality %></td>
        <td><%= rating.encroachment %></td>
        <td><%= rating.platform_usability %></td>
        <td><%= rating.safety %></td>
        <td><%= rating.comments %></td>
        <td><%= rating.road.summary %></td>
        <td><%= rating.user.email %></td>
        <td><%= rating.status %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Road quality:</strong>
  <%= @rating.road_quality %>
</p>

<p>
  <strong>Encroachment:</strong>
  <%= @rating.encroachment %>
</p>

<p>
  <strong>Platform usability:</strong>
  <%= @rating.platform_usability %>
</p>

<p>
  <strong>Safety:</strong>
  <%= @rating.safety %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @rating.comments %>
</p>

<p>
  <strong>Road:</strong>
  <%= @rating.road_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag @rating.photo.url %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>